# Generated by Django 4.0.2 on 2022-02-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_content_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(
                default="ZC Blog | <django.db.models.fields.CharField>",
                max_length=200,
                unique=True,
            ),
        ),
    ]
