# Generated by Django 4.0.2 on 2022-02-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_post_title_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="title_tag",
        ),
    ]
