# Generated by Django 4.0.2 on 2022-02-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_post_title_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="titel", max_length=200),
        ),
    ]
