# Generated by Django 4.0.2 on 2022-02-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_post_title_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="Zeise Coding Blog", max_length=200),
        ),
    ]
