# Generated by Django 4.0.2 on 2022-02-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_category_alter_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
    ]
