# Generated by Django 4.0.2 on 2022-03-10 16:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0033_profile_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="snippet",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, max_length=200, null=True
            ),
        ),
    ]
