# Generated by Django 4.0.2 on 2022-03-15 16:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0035_delete_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content_upload",
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
