# Generated by Django 4.0.2 on 2022-03-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0036_remove_post_content_upload_alter_post_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
    ]
