# Generated by Django 4.0.6 on 2022-08-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_delete_courselist"),
        ("blog", "0040_alter_post_author_alter_post_content_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Picture",
            new_name="Image",
        ),
    ]
