# Generated by Django 4.0.6 on 2022-09-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_post_vg_wort_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
