# Generated by Django 4.0.2 on 2022-03-10 17:07

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "snippet",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, max_length=200, null=True
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/profile/"
                    ),
                ),
                (
                    "website_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("github_url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "linkedin_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("reddit_url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "instagram_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "pinterest_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "twitter_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "facebook_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
