# Generated by Django 4.0.5 on 2022-08-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_courselist_course_created_on_course_pin_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseList",
        ),
    ]
