# Generated by Django 4.0.6 on 2022-09-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_discount_course_discount_link_course_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
