# Generated by Django 4.0.6 on 2022-09-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_slug_alter_course_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='discount',
            new_name='discount_price',
        ),
    ]
